require 'spec_helper'
require 'gyoku'

describe Gyoku do
  def oneline_xml(input)
    input.gsub("\n", '').gsub(/>[ ]*</, '><').strip
  end
  
  it "converts a complex Hash into XML" do
    hash = {
      :outer => {
        :gem => "Gyoku",
        :inner => {
          :title => "List",
          :attributes! => {:title => {:count => 2}},
          :items => {
            :item => [
              {
                :name => "Foo"
              },
              {
                :name => "Bar"
              }
            ],
            :attributes! => {:item => {:type => ['Baz', 'Foz']}}
          }
        }
      }
    }
    
    generated_xml = Gyoku.xml(hash)
    
    xml = <<-XML
      <outer>
        <gem>Gyoku</gem>
        <inner>
          <title count="2">List</title>
          <items>
            <item type="Baz"><name>Foo</name></item>
            <item type="Foz"><name>Bar</name></item>
          </items>
        </inner>
      </outer>
    XML
    
    generated_xml.should == oneline_xml(xml)
  end
  
  it "does not support @ prefixed keys, as generated by Nori" do
    # if this tests fails, then it is a good thing.  Until then
    # it is seen as a limitation that must be coded around
    
    hash = {
      :item => {
        :name => "Foo",
        "@type" => "Bar"
      }
    }
    
    generated_xml = Gyoku.xml(hash)
    
    desired_xml = <<-XML
      <item type="Bar">
        <name>Foo</name>
      </item>
    XML
    
    actual_xml = <<-XML
      <item>
        <name>Foo</name>
        <@type>Bar</@type>
      </item>
    XML
    
    generated_xml.should_not == oneline_xml(desired_xml)
    generated_xml.should == oneline_xml(actual_xml)
  end
end